database-connector.js
database-constants.js
mongo-queries.js
session-middleware.js

- add session middleware
- add constants
- update MongDB connector

add session middleware

---

constants/user-constants.js
mongodb-collection.js

- Add user constants
- Standardize error throwing

User Constants

---

constants/monogodb-constants.js
services/user.js
utility/mongodb-utility.js

User constant & Verifying admin role

listApplications

---

database-constants.js

Added test codes
- organization services Added organization collections

Added organization services

---

services/user.js

- changed "organizations" to "organization"
- initialize organization with an empty object
- if there is no first name, then the email before the @ symbol is used to set the firstname until it is updated

update user creation

---

constants/event-constants.js
constants/user-constants.js
database-constants.js
domain/log-events.js
services/user.js

1. Added Log Events
2. Updated getMyUser to store logging
3. Added Mongodb log collection

Log Events

---

constants/user-constants.js
domain/log-events.js
mongodb-collection.js

added an option for the update query.

Save application history

---

domain/log-events.js

login & logout logs

---

constants/user-constants.js
services/user.js

Added user-roles
Added admin-user emails

User-Control

---

services/user.js

Added getAdmin to get all user with role: "Admin"

Added getAdmin

---

session-middleware.js

Implemented the changes to createSessions for retrieving session time from the cookies.

Updated session-middleware to accommodate the session-ttl changes

---

constants/error-constants.js
database-constants.js
mongodb-collection.js
utility/string-utility.js

1. JSON Parse Utility & Error Code
2. Monogo db collection constant

Approved studies

---

services/user.js

Added getConcierge to retrieve concierge from the User collection

Added getConcierge

---

constants/user-constants.js
services/user.js

Replace all instances of "Disabled" user status with "Inactive"

Remove disabled user status

---

database-constants.js

Adds the dataSubmissions constant.

Crdcdh 114 310 add `dataSubmissions` collection. 

---

database-constants.js

Try to read database name from env var DATABASE_NAME, before using default DB name

Read database name from env var DATABASE_NAME

---

constants/organization-constants.js
services/organization.js
services/user.js

This reverts commit 02c8ed1493f9a58f5867740da7af84db689def3a.

Restore the Revert Commit 02c8ed1

---

database-constants.js

changing the collection name to submissions.

changing dataSubmissions to submissions

---

services/user.js

email notification to an inactive user

inactive user notification

---

services/user.js

Added grantToken and linkTokentoUser in User Services as part of CRDCDH-118

Added grantTokens function in user services

---

services/organization.js

Changing api to match updated ticket requirements. All logged in users can access listOrganization api.

listOrganization api changes

---

services/organization.js

This PR modifies the implementation of `editOrganization` to also change dependent data models when the organization name changes.
Models included:
* Users (`organization.orgName`)
* Data Submissions (`organization.name`)
* Submission Requests (`organization.name`)
Not included:
* Approved Studies (`approvedStudy.originalOrg`) – No Org ID to query off of
https://github.com/CBIIT/crdc-datahub-authz/pull/48
https://tracker.nci.nih.gov/browse/CRDCDH-353

CRDCDH-353 Update dependent objects with name change

---

constants/event-constants.js
domain/log-events.js

updated for the ticket, crdcdh-462, submission workflow/actions.

add submissionn events

---

services/s3-service.js

updated content type header

---

domain/approved-studies.js
services/organization.js

Added approved studies in the organization service

Store the approved studies into the organization

---

services/user.js

Update user token

---

services/organization.js

This PR removes the `/` prefix on the `rootPath` property per updated requirements.

Remove Organizaton `rootPath` prefix

---

mongodb-collection.js

Add distinct query for collections

CRDCDH-696

---

mongodb-collection.js

add countDoc function in MongoDBCollection.js

fix crdcdh-880

---

services/organization.js

remove uniqueness constraint on study abbreviation.

CRDCDH-907

---

services/user.js

Email Notification - Inactive Users
- inactive users keep getting email notifications

[Bug] Email Notification - Inactive Users

---

services/user.js

inactive users keep getting email notifications

[Bug] Inactive User Email Notification

---

database-constants.js
mongodb-collection.js

Added institution collection constant
Added findAll function to MongoDBCollection

CRDCDH-1127

---

services/s3-service.js

implemented 1217

---

constants/error-constants.js
services/organization.js

The update/create organization needs to be modified.

update/create organization API

---

constants/user-constants.js

CRDCDH-1508

---

services/user.js

get a list of federal monitors

CRDCDH-1509

---

constants/error-constants.js
services/user.js
utility/string-utility.js

Implemented [CRDCDH-1505](https://tracker.nci.nih.gov/browse/CRDCDH-1505)
BE: API allows assigning Federal Monitor role

Crdcdh 1505 db 001 pgu
